  frontend:
    build:
      context: ../calendario-frontend
      dockerfile: Dockerfile
    container_name: calendario_frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8000
    volumes:
      - ../calendario-frontend:/app
      - /app/node_modules
    depends_on:
      - web