import { useEffect, useRef, useState } from 'react'
import { assignOrReplace, cancelPending, getAssignableAreaTemplates, getState } from '../../calendarArea/services/areaTemplateAssignmentsService'

const items = (data) => Array.isArray(data) ? data : data?.results || []
const templateId = (template) => template.id_area_template ?? template.id
const templateName = (template) => template.name ?? template.nombre
const templateVersion = (template) => template.current_version?.version ?? template.version ?? template.current_version_number
const actionAllowed = (actions, name) => Array.isArray(actions) ? actions.includes(name) : actions?.[name] === true
const errorMessage = (error, fallback) => error?.status === 403 ? 'No tienes permisos para asignar plantillas a esta área.' : error?.message || fallback

export default function AreaTemplateAssignmentModal({ area, onClose }) {
  const dialogRef = useRef(null); const previousFocus = useRef(null)
  const [state, setState] = useState(null); const [templates, setTemplates] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const [selected, setSelected] = useState(''); const [startDate, setStartDate] = useState(''); const [confirmCancel, setConfirmCancel] = useState(false)
  async function load() { setLoading(true); setError(''); try { const [assignment, catalog] = await Promise.all([getState(area.id), getAssignableAreaTemplates(area.id)]); setState(assignment); setTemplates(items(catalog)) } catch (requestError) { setError(errorMessage(requestError, 'No se pudo cargar la asignación de plantilla.')) } finally { setLoading(false) } }
  useEffect(() => { previousFocus.current = document.activeElement; dialogRef.current?.focus(); void load(); return () => previousFocus.current?.focus() }, [area.id])
  function keyDown(event) { if (event.key === 'Escape') { event.preventDefault(); onClose(); return } if (event.key !== 'Tab') return; const nodes = [...dialogRef.current.querySelectorAll('button:not([disabled]), input:not([disabled]), select:not([disabled])')]; const first = nodes[0]; const last = nodes.at(-1); if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus() } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus() } }
  const assignment = state?.assignment ?? state?.current_assignment ?? state?.current
  const pending = state?.pending_assignment ?? state?.pending
  const canAssign = actionAllowed(state?.actions, assignment ? 'replace' : 'assign')
  const canCancel = actionAllowed(state?.actions, 'cancel_pending') && pending
  async function submit(event) { event.preventDefault(); const template = templates.find((item) => String(templateId(item)) === selected); if (!template) return; setSaving(true); setError(''); try { await assignOrReplace(area.id, { template_id: templateId(template), version: templateVersion(template), ...(startDate ? { fecha_inicio: startDate } : {}) }); await load() } catch (requestError) { setError(errorMessage(requestError, 'No se pudo guardar la asignación.')) } finally { setSaving(false) } }
  async function cancel() { setSaving(true); setError(''); try { await cancelPending(area.id, pending.id ?? pending.id_assignment); setConfirmCancel(false); await load() } catch (requestError) { setError(errorMessage(requestError, 'No se pudo cancelar la asignación futura.')) } finally { setSaving(false) } }
  return <div className="areas-modal-backdrop"><section ref={dialogRef} className="areas-modal area-template-assignment-modal" role="dialog" aria-modal="true" aria-label={`Plantilla de área para ${area.nombre}`} tabIndex="-1" onKeyDown={keyDown}><header><h2>Plantilla de área para {area.nombre}</h2><button className="areas-modal-close" type="button" aria-label="Cerrar" onClick={onClose}>×</button></header><div className="areas-modal-content">{loading ? <p role="status">Cargando asignación de plantilla...</p> : error && !state ? <div role="alert"><p>{error}</p><button type="button" onClick={load}>Reintentar</button></div> : <><section className="area-template-state"><h3>Asignación actual</h3>{assignment ? <p><strong>{templateName(assignment.template ?? assignment)}</strong> · versión {assignment.version ?? templateVersion(assignment.template)}</p> : <p>Esta área no tiene una plantilla asignada.</p>}{pending && <p>Reemplazo futuro: <strong>{templateName(pending.template ?? pending)}</strong>{pending.fecha_inicio ? ` desde ${pending.fecha_inicio}` : ''}.</p>}</section>{error && <p role="alert">{error}</p>}{canAssign && <form onSubmit={submit}><label>Plantilla<select data-autofocus value={selected} onChange={(event) => setSelected(event.target.value)} disabled={saving} required><option value="">Seleccionar plantilla</option>{templates.map((template) => <option key={templateId(template)} value={templateId(template)}>{templateName(template)} · versión {templateVersion(template)}</option>)}</select></label><label>Fecha de inicio <span>(opcional)</span><input type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} disabled={saving} /></label><button disabled={!selected || saving}>{saving ? 'Guardando...' : assignment ? 'Reemplazar plantilla' : 'Asignar plantilla'}</button></form>}{!canAssign && <p>No hay acciones de asignación disponibles para esta área.</p>}{canCancel && (confirmCancel ? <div className="area-template-confirm"><p>¿Deseas cancelar el reemplazo futuro?</p><button type="button" className="areas-danger" disabled={saving} onClick={cancel}>{saving ? 'Cancelando...' : 'Confirmar cancelación'}</button><button type="button" className="btn-secondary" onClick={() => setConfirmCancel(false)}>Volver</button></div> : <button type="button" className="btn-secondary" onClick={() => setConfirmCancel(true)}>Cancelar reemplazo futuro</button>)}</>}</div></section></div>
}
